package disclosure

import (
	"strings"
	"testing"

	"github.com/powerformer/looper/internal/config"
)

func TestCommitMessageAddsTrailerWithoutChangingSubject(t *testing.T) {
	s := testStamper()
	got := s.CommitMessage("feat: add thing", "worker")
	if !strings.HasPrefix(got, "feat: add thing\n") {
		t.Fatalf("subject changed: %q", got)
	}
	if !strings.Contains(got, "Generated-By: looper 1.2.3 (runner=worker, agent=claude-code)") {
		t.Fatalf("missing trailer: %q", got)
	}
}

func TestCommitMessageIsIdempotent(t *testing.T) {
	s := testStamper()
	first := s.CommitMessage("fix: bug", "worker")
	second := s.CommitMessage(first, "fixer")
	if strings.Count(second, "Generated-By: looper") != 1 {
		t.Fatalf("duplicate trailer: %q", second)
	}
	if !strings.Contains(second, "runner=fixer") {
		t.Fatalf("trailer was not replaced: %q", second)
	}
}

func TestMarkdownFooterIsIdempotent(t *testing.T) {
	s := testStamper()
	first := s.Markdown("Body", "reviewer", ChannelIssueComment)
	second := s.Markdown(first, "worker", ChannelIssueComment)
	if strings.Count(second, Marker) != 1 {
		t.Fatalf("duplicate marker: %q", second)
	}
	if !strings.Contains(second, "Generated by looper 1.2.3 · runner=worker · agent=claude-code") {
		t.Fatalf("footer was not replaced: %q", second)
	}
}

func TestReviewCommentDefaultsToHiddenMarker(t *testing.T) {
	s := testStamper()
	got := s.ReviewComment("Inline note", "reviewer")
	if strings.Contains(got, "Generated by looper") {
		t.Fatalf("visible inline disclosure included by default: %q", got)
	}
	if strings.Count(got, Marker) != 1 {
		t.Fatalf("missing hidden marker: %q", got)
	}
}

func TestDisabledDisclosureLeavesContentUntouched(t *testing.T) {
	s := testStamper()
	s.Config.Enabled = false
	if got := s.Markdown("Body", "worker", ChannelPullRequest); got != "Body" {
		t.Fatalf("Markdown() = %q, want Body", got)
	}
	if got := s.CommitMessage("feat: subject", "worker"); got != "feat: subject" {
		t.Fatalf("CommitMessage() = %q, want original", got)
	}
}

func TestDisclosureUsesAllowlistedMachineDetails(t *testing.T) {
	s := testStamper()
	s.Config.IncludeOS = true
	got := s.Markdown("Body", "worker", ChannelPullRequest)
	for _, forbidden := range []string{"hostname", "username", "/Users/", "/tmp/", "127.0.0.1", "192.168.", "10.0.", "TOKEN", "HOME="} {
		if strings.Contains(got, forbidden) {
			t.Fatalf("disclosure included forbidden detail %q: %q", forbidden, got)
		}
	}
	if strings.Contains(got, "darwin") || strings.Contains(got, "linux") || strings.Contains(got, "windows") {
		t.Fatalf("disclosure included raw GOOS instead of OS family: %q", got)
	}
}

func testStamper() Stamper {
	return Stamper{
		Version: "1.2.3",
		Agent:   "claude-code",
		Config: config.DisclosureConfig{
			Enabled:      true,
			IncludeAgent: true,
			IncludeOS:    false,
			Channels: config.DisclosureChannelsConfig{
				GitCommit:            true,
				PullRequest:          true,
				IssueComment:         true,
				ReviewComment:        true,
				InlineCommentVisible: false,
			},
		},
	}
}
