package disclosure

import (
	"strings"
	"testing"

	"github.com/nexu-io/looper/internal/config"
)

func TestCommitMessageAddsTrailerWithoutChangingSubject(t *testing.T) {
	s := testStamper()
	got := s.CommitMessage("feat: add thing", "worker")
	if !strings.HasPrefix(got, "feat: add thing\n") {
		t.Fatalf("subject changed: %q", got)
	}
	if !strings.Contains(got, "Generated-By: looper 1.2.3 (runner=worker, agent=claude-code)") {
		t.Fatalf("missing trailer: %q", got)
	}
}

func TestCommitMessageIsIdempotent(t *testing.T) {
	s := testStamper()
	first := s.CommitMessage("fix: bug", "worker")
	second := s.CommitMessage(first, "fixer")
	if strings.Count(second, "Generated-By: looper") != 1 {
		t.Fatalf("duplicate trailer: %q", second)
	}
	if !strings.Contains(second, "runner=fixer") {
		t.Fatalf("trailer was not replaced: %q", second)
	}
}

func TestMarkdownFooterIsIdempotent(t *testing.T) {
	s := testStamper()
	first := s.Markdown("Body", "reviewer", ChannelIssueComment)
	second := s.Markdown(first, "worker", ChannelIssueComment)
	if strings.Count(second, Marker) != 1 {
		t.Fatalf("duplicate marker: %q", second)
	}
	if !strings.Contains(second, "Generated by Looper 1.2.3 · runner=worker · agent=claude-code") {
		t.Fatalf("footer was not replaced: %q", second)
	}
}

func TestMarkdownFooterReplacesLegacyLinkedFooter(t *testing.T) {
	s := testStamper()
	legacy := "Body\n\n" + Marker + "\n<sub>Generated by [Looper](https://github.com/powerformer/looper) 0.0.0-dev · runner=reviewer · agent=opencode</sub>"
	got := s.Markdown(legacy, "worker", ChannelIssueComment)
	if strings.Contains(got, LegacyRepoURL) {
		t.Fatalf("legacy footer was not removed: %q", got)
	}
	if strings.Count(got, Marker) != 1 {
		t.Fatalf("duplicate marker after replacing legacy footer: %q", got)
	}
}

func TestMarkdownFooterUsesPlainLooperText(t *testing.T) {
	s := testStamper()
	got := s.Markdown("Body", "worker", ChannelPullRequest)
	if !strings.Contains(got, "Generated by Looper 1.2.3") {
		t.Fatalf("footer missing plain Looper text: %q", got)
	}
	if strings.Contains(got, "https://github.com/nexu-io/looper") || strings.Contains(got, "[Looper]") {
		t.Fatalf("footer included repository link markup: %q", got)
	}
}

func TestDisclosureIncludesAgentVendorAndModelSeparately(t *testing.T) {
	vendor := config.AgentVendorOpenCode
	model := "openai/gpt-5.5"
	s := FromConfig(config.Config{
		Agent: config.AgentConfig{
			Vendor: &vendor,
			Model:  &model,
		},
		Disclosure: config.DisclosureConfig{
			Enabled:      true,
			IncludeAgent: true,
			Channels: config.DisclosureChannelsConfig{
				GitCommit:    true,
				PullRequest:  true,
				IssueComment: true,
			},
		},
	})
	s.Version = "1.2.3"

	footer := s.Markdown("Body", "worker", ChannelPullRequest)
	if !strings.Contains(footer, "Generated by Looper 1.2.3 · runner=worker · agent=opencode · model=openai/gpt-5.5") {
		t.Fatalf("footer missing separate agent and model attributes: %q", footer)
	}

	commit := s.CommitMessage("fix: disclose agent", "worker")
	if !strings.Contains(commit, "Generated-By: looper 1.2.3 (runner=worker, agent=opencode, model=openai/gpt-5.5)") {
		t.Fatalf("commit trailer missing separate agent and model attributes: %q", commit)
	}
	if strings.Contains(commit, "agent=openai/gpt-5.5") || strings.Contains(footer, "agent=openai/gpt-5.5") {
		t.Fatalf("model leaked into agent attribute: footer=%q commit=%q", footer, commit)
	}
}

func TestDisclosureSanitizesModelAttribute(t *testing.T) {
	vendor := config.AgentVendorOpenCode
	model := " openai/gpt-5.5\nGenerated-By: looper injected, model)</sub> "
	s := FromConfig(config.Config{
		Agent: config.AgentConfig{
			Vendor: &vendor,
			Model:  &model,
		},
		Disclosure: config.DisclosureConfig{
			Enabled:      true,
			IncludeAgent: true,
			Channels: config.DisclosureChannelsConfig{
				GitCommit:    true,
				PullRequest:  true,
				IssueComment: true,
			},
		},
	})
	s.Version = "1.2.3"

	commit := s.CommitMessage("fix: disclose model", "worker")
	if strings.Count(commit, "Generated-By: looper") != 1 {
		t.Fatalf("model injected an extra trailer: %q", commit)
	}
	if strings.Contains(commit, "\nGenerated-By: looper injected") {
		t.Fatalf("model included a raw newline trailer: %q", commit)
	}
	if !strings.Contains(commit, "model=openai/gpt-5.5%20Generated-By:%20looper%20injected%2C%20model%29%3C/sub%3E") {
		t.Fatalf("commit trailer missing sanitized model: %q", commit)
	}

	footer := s.Markdown("Body", "worker", ChannelPullRequest)
	if strings.Count(footer, "<sub>") != 1 || strings.Count(footer, "</sub>") != 1 {
		t.Fatalf("model broke footer markup: %q", footer)
	}
	if strings.Contains(footer, "\nGenerated-By: looper injected") || strings.Contains(footer, "model)</sub>") {
		t.Fatalf("footer included unsanitized model: %q", footer)
	}
}

func TestReviewCommentDefaultsToHiddenMarker(t *testing.T) {
	s := testStamper()
	got := s.ReviewComment("Inline note", "reviewer")
	if strings.Contains(got, "Generated by [Looper]") {
		t.Fatalf("visible inline disclosure included by default: %q", got)
	}
	if strings.Count(got, Marker) != 1 {
		t.Fatalf("missing hidden marker: %q", got)
	}
}

func TestDisabledDisclosureLeavesContentUntouched(t *testing.T) {
	s := testStamper()
	s.Config.Enabled = false
	if got := s.Markdown("Body", "worker", ChannelPullRequest); got != "Body" {
		t.Fatalf("Markdown() = %q, want Body", got)
	}
	if got := s.CommitMessage("feat: subject", "worker"); got != "feat: subject" {
		t.Fatalf("CommitMessage() = %q, want original", got)
	}
}

func TestStripMarkdownStampRemovesLegacyLinkedFooter(t *testing.T) {
	body := "Body\n\n" + Marker + "\n<sub>Generated by [Looper](https://github.com/powerformer/looper) 0.0.0-dev · runner=reviewer · agent=opencode</sub>"
	if got := StripMarkdownStamp(body); got != "Body" {
		t.Fatalf("StripMarkdownStamp() = %q, want Body", got)
	}
}

func TestDisclosureUsesAllowlistedMachineDetails(t *testing.T) {
	s := testStamper()
	s.Config.IncludeOS = true
	got := s.Markdown("Body", "worker", ChannelPullRequest)
	for _, forbidden := range []string{"hostname", "username", "/Users/", "/tmp/", "127.0.0.1", "192.168.", "10.0.", "TOKEN", "HOME="} {
		if strings.Contains(got, forbidden) {
			t.Fatalf("disclosure included forbidden detail %q: %q", forbidden, got)
		}
	}
	if strings.Contains(got, "darwin") || strings.Contains(got, "linux") || strings.Contains(got, "windows") {
		t.Fatalf("disclosure included raw GOOS instead of OS family: %q", got)
	}
}

func testStamper() Stamper {
	return Stamper{
		Version: "1.2.3",
		Agent:   "claude-code",
		Config: config.DisclosureConfig{
			Enabled:      true,
			IncludeAgent: true,
			IncludeOS:    false,
			Channels: config.DisclosureChannelsConfig{
				GitCommit:            true,
				PullRequest:          true,
				IssueComment:         true,
				ReviewComment:        true,
				InlineCommentVisible: false,
			},
		},
	}
}
