import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDir, "..");
const repoRoot = join(packageRoot, "..", "..");
const cliPackageJsonPath = join(repoRoot, "apps", "cli", "package.json");
const migrationsDir = join(
  packageRoot,
  "src",
  "storage",
  "sqlite",
  "migrations",
);
const generatedVersionPath = join(
  packageRoot,
  "src",
  "generated",
  "version.ts",
);
const generatedMigrationsPath = join(
  packageRoot,
  "src",
  "storage",
  "sqlite",
  "migrations.gen.ts",
);

const MIGRATION_FILE_RE = /^(\d{4}_[a-zA-Z0-9_\-]+)\.sql$/;

interface CliPackageJson {
  version: string;
}

function readOptionalBuildValue(envName: string): string | null {
  const value = process.env[envName]?.trim();
  return value ? value : null;
}

function renderMigration(migration: {
  fileName: string;
  id: string;
  sql: string;
}): string {
  return [
    "  {",
    `    fileName: ${JSON.stringify(migration.fileName)},`,
    `    id: ${JSON.stringify(migration.id)},`,
    `    sql: ${JSON.stringify(migration.sql)},`,
    "  },",
  ].join("\n");
}

async function main() {
  const cliPackageJson = JSON.parse(
    await readFile(cliPackageJsonPath, "utf8"),
  ) as CliPackageJson;
  const buildMetadata = {
    versionSource: "apps/cli/package.json",
    gitCommitSha: readOptionalBuildValue("LOOPER_BUILD_GIT_SHA"),
    buildTimestamp: readOptionalBuildValue("LOOPER_BUILD_TIMESTAMP"),
  };
  const migrationEntries = (await readdir(migrationsDir))
    .filter((entry) => MIGRATION_FILE_RE.test(entry))
    .sort();

  const migrations = await Promise.all(
    migrationEntries.map(async (fileName) => ({
      fileName,
      id: fileName.replace(/\.sql$/, ""),
      sql: await readFile(join(migrationsDir, fileName), "utf8"),
    })),
  );

  await mkdir(dirname(generatedVersionPath), { recursive: true });
  await writeFile(
    generatedVersionPath,
    [
      "// AUTO-GENERATED by apps/looperd/scripts/generate-artifacts.ts",
      "// Source of truth: apps/cli/package.json",
      "export interface LooperdBuildMetadata {",
      "  versionSource: string;",
      "  gitCommitSha: string | null;",
      "  buildTimestamp: string | null;",
      "}",
      "",
      `export const LOOPERD_VERSION = ${JSON.stringify(cliPackageJson.version)};`,
      `export const LOOPERD_BUILD_METADATA: LooperdBuildMetadata = ${JSON.stringify(buildMetadata)};`,
      "",
    ].join("\n"),
  );

  await writeFile(
    generatedMigrationsPath,
    [
      "// AUTO-GENERATED by apps/looperd/scripts/generate-artifacts.ts",
      "// Source of truth: apps/looperd/src/storage/sqlite/migrations/*.sql",
      "export interface EmbeddedSqliteMigration {",
      "  id: string;",
      "  fileName: string;",
      "  sql: string;",
      "}",
      "",
      "export const SQLITE_MIGRATIONS: EmbeddedSqliteMigration[] = [",
      ...migrations.map(renderMigration),
      "];",
      "",
    ].join("\n"),
  );
}

await main();
